application:
  port: 8000
  base_url: "http://127.0.0.1"
database_url: "postgres://postgres:postgres@0.0.0.0:5432/newsletter"
email_client:
  base_url: "localhost"
  sender_email: "test@test.com"
  auth_token: "my-auth-token"
  timeout_milliseconds: 1000
